# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 5b3a3433c0064d0bf4804caecea75b0bf9a5a581c234d7ff87d8fe827d04e3c8a10926d2dd90149e9ec879514b951d6dca8c95cea32c4d1d84dd506647c66c02

test:
  secret_key_base: b5c2b4a8ec538f457227531b0a2b8e749fd1043f0477252be97d1c4e03c4201eaf52823f951ea9f129511e43e1c851d6c140a618f30362d2b8ed3ab30607595c

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
